name: torganic
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1


environment:
  sdk: '>=3.3.1 <4.0.0'

#----------Packages----------#
dependencies:
  flutter:
    sdk: flutter


  #Utility Packages
  http: ^1.2.1
  intl: any
  logger: ^2.1.0
  lottie: ^3.1.0
  url_launcher: ^6.2.5
  connectivity_plus: ^5.0.2
  connection_notifier: ^2.0.1
  carousel_slider: ^4.2.1
  another_flushbar: ^1.12.30
  smooth_page_indicator: ^1.1.0
  persistent_bottom_nav_bar: any
  persistent_bottom_nav_bar_v2: any
  buttons_tabbar: ^1.3.8
  fluttertoast: ^8.2.4
  google_fonts: ^6.2.1
  gap: ^3.0.1

  # Icons
  cupertino_icons: ^1.0.6


  #State Management
  get: ^4.6.6
  get_storage: ^2.1.1

  #Local Strorage
  shared_preferences: ^2.2.2

  # Localization
  flutter_localizations:
    sdk: flutter



dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^3.0.0


flutter:

  generate: true
  uses-material-design: true

  # Local Assets
  assets:
    - assets/images/logos/
    - assets/images/animations/
    - assets/images/banners/
    - assets/images/on_boarding_images/


  # Local Fonts
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         styles: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
